---
- name: Deploy HookRelay App
  hosts: service_incall
  remote_user: ubuntu
  become: True
  become_method: sudo
  become_user: root

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    app_user: "{{ ansible_user }}"
    app_name: hookrelay
    log_dir: "/var/log/app/{{ app_name }}"
    config_dir: "/etc/{{ app_name }}"
    repo_url: "https://github.com/codeasashu/HookRelay"
    s3_config_path: "s3://my-bucket/hookrelay/config.toml"

  tasks:
    - name: Install required packages
      apt:
        name:
          - supervisor
        update_cache: true

    - name: Ensure log directory exists
      file:
        path: "{{ log_dir }}"
        state: directory
        mode: "0755"

    - name: Create temp directory for building
      tempfile:
        state: directory
        suffix: hookrelay
      register: tempdir

    - import_tasks: git.yml
      name: Git clone

    - name: Build the application
      command: ./build.sh linux
      args:
        chdir: "{{ tempdir.path }}"

    - name: Deploy the application
      command: ./deploy.sh
      args:
        chdir: "{{ tempdir.path }}"

    - name: Ensure config directory exists
      file:
        path: "{{ config_dir }}"
        state: directory
        mode: "0755"

    - name: Download config.toml from S3
      command: aws s3 cp "{{ s3_config_path }}" "{{ config_dir }}/config.toml"
      environment:
        AWS_REGION: "us-east-1" # or your relevant region

    - name: Restart HookRelay supervisor process
      command: supervisorctl restart hookrelay:*
