services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis

  mysql:
    image: mysql:8
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_PASSWORD=${DB_PASSWORD:-12345678}
      - MYSQL_USER=hookrelay
      - MYSQL_DATABASE=hookrelay

volumes:
  redis_data:
  mysql_data:
