# Configuration file for HookRelay
# http listener config
[listener]
http.port = 8082
http.queue_size = 1024
http.workers = 4

[api]
port = 8081

[worker]
scan_duration = 100
min_threads = 50
max_threads = 100

[metrics]
enabled = true
