global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: hookrelay
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8081"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8098"]
